name: Build

on: [push]

jobs:
  build-client:
    name: client ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "windows_x64_msvc"
          os: windows-latest
          generator: "Visual Studio 16 2019"
          arch: "-A x64"
          target: traintastic-client
          build_type: Release
          defines: ""

        - name: "ubuntu_18.04"
          os: ubuntu-18.04
          generator: "Unix Makefiles"
          arch: ""
          target: traintastic-client
          build_type: Release
          defines: "-DDEBIAN_PACKAGE_VERSION_EXTRA=~ubuntu~bionic~$CI_REF_NAME_SLUG~${{github.run_number}}~$CI_SHA_SHORT"

        - name: "ubuntu_20.04"
          os: ubuntu-20.04
          generator: "Unix Makefiles"
          arch: ""
          target: traintastic-client
          build_type: Release
          defines: "-DDEBIAN_PACKAGE_VERSION_EXTRA=~ubuntu~focal~$CI_REF_NAME_SLUG~${{github.run_number}}~$CI_SHA_SHORT"

    steps:
    # All:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    # All:
    - name: Checkout LFS objects
      run: git lfs checkout

    # Windows only:
    - name: Cache Qt
      if: startswith(matrix.config.os, 'windows')
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{runner.os}}-QtCache

    # Windows only:
    - name: Install Qt
      if: startswith(matrix.config.os, 'windows')
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{steps.cache-qt.outputs.cache-hit}}

    # Ubuntu only:
    - name: apt update
      if: startswith(matrix.config.os, 'ubuntu')
      run: sudo apt update

    # Ubuntu only:
    - name: Install packages
      if: startswith(matrix.config.os, 'ubuntu')
      run: sudo apt install qt5-default

    # Windows only:
    - name: Setup Microsoft Visual Studio 2019 Environment
      if: startswith(matrix.config.os, 'windows')
      shell: cmd
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    # All:
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/client/build

    # All:
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/client/build
      run: cmake $GITHUB_WORKSPACE/client -G "${{matrix.config.generator}}" ${{matrix.config.arch}} -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.defines}}

    # All:
    - name: Build
      working-directory: ${{runner.workspace}}/client/build
      shell: bash
      run: cmake --build . --config ${{matrix.config.build_type}} --target ${{matrix.config.target}}

    # Windows only:
    - name: Run windeployqt
      if: startswith(matrix.config.os, 'windows')
      shell: cmd
      run: windeployqt --release --no-translations -no-system-d3d-compiler --no-opengl-sw ${{runner.workspace}}/build/traintastic-client.exe

    # Ubuntu only:
    - name: Build debian package
      if: startswith(matrix.config.os, 'ubuntu') && matrix.config.target == 'traintastic-client'
      working-directory: ${{runner.workspace}}/client/build
      run: cpack

    # Windows only:
    - name: Upload artifact
      if: startswith(matrix.config.os, 'windows')
      uses: actions/upload-artifact@v2
      with:
        name: traintastic-client
        path: ${{runner.workspace}}/build

    # Ubuntu only:
    - name: Upload artifact
      if: startswith(matrix.config.os, 'ubuntu') && matrix.config.target == 'traintastic-client'
      uses: actions/upload-artifact@v2
      with:
        name: traintastic-client-deb
        path: ${{runner.workspace}}/client/build/*.deb

  build-server:
    name: server ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "windows_x64_clang"
          os: windows-latest
          generator: "Visual Studio 16 2019"
          arch: "-A x64"
          toolset: "-T ClangCL"
          target: traintastic-server
          build_type: Release
          defines: ""
          ccov: false

        - name: "windows_x64_clang (test)"
          os: windows-latest
          generator: "Visual Studio 16 2019"
          arch: "-A x64"
          toolset: "-T ClangCL"
          target: traintastic-server-test
          build_type: Release
          defines: ""
          ccov: false

        - name: "ubuntu_18.04"
          os: ubuntu-18.04
          generator: "Unix Makefiles"
          arch: ""
          toolset: ""
          target: traintastic-server
          build_type: Release
          defines: "-DDEBIAN_PACKAGE_VERSION_EXTRA=~ubuntu~bionic~$CI_REF_NAME_SLUG~${{github.run_number}}~$CI_SHA_SHORT"
          ccov: false

        - name: "ubuntu_18.04 (test)"
          os: ubuntu-18.04
          generator: "Unix Makefiles"
          arch: ""
          toolset: ""
          target: traintastic-server-test
          build_type: Release
          defines: ""
          ccov: false

        - name: "ubuntu_20.04"
          os: ubuntu-20.04
          generator: "Unix Makefiles"
          arch: ""
          toolset: ""
          target: traintastic-server
          build_type: Release
          defines: "-DDEBIAN_PACKAGE_VERSION_EXTRA=~ubuntu~focal~$CI_REF_NAME_SLUG~${{github.run_number}}~$CI_SHA_SHORT"
          ccov: false

        - name: "ubuntu_20.04 (test+ccov)"
          os: ubuntu-20.04
          generator: "Unix Makefiles"
          arch: ""
          toolset: ""
          target: traintastic-server-test
          build_type: Debug
          defines: "-DCODE_COVERAGE=ON"
          ccov: true

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    # All:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    # All:
    - name: Checkout LFS objects
      run: git lfs checkout

    # Ubuntu only:
    - name: Install packages
      if: startswith(matrix.config.os, 'ubuntu')
      run: sudo apt install liblua5.3-dev lcov

    # All:
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/server/build

    # All:
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/server/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE/server -G "${{matrix.config.generator}}" ${{matrix.config.arch}} ${{matrix.config.toolset}} -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DUSB_XPRESSNET=OFF ${{matrix.config.defines}}

    # All:
    - name: Build
      working-directory: ${{runner.workspace}}/server/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{matrix.config.build_type}} --target ${{matrix.config.target}}

    # All:
    - name: Run tests
      if: matrix.config.target == 'traintastic-server-test'
      working-directory: ${{runner.workspace}}/server/build
      run: ctest --output-on-failure

    # Ubuntu only:
    - name: Build debian package
      if: startswith(matrix.config.os, 'ubuntu') && matrix.config.target == 'traintastic-server'
      working-directory: ${{runner.workspace}}/server/build
      run: cpack

    # Windows only:
    - name: Upload artifact
      if: startswith(matrix.config.os, 'windows') && matrix.config.target == 'traintastic-server'
      uses: actions/upload-artifact@v2
      with:
        name: traintastic-server
        path: ${{runner.workspace}}/server/build/Release

    # Ubuntu only:
    - name: Upload artifact
      if: startswith(matrix.config.os, 'ubuntu') && matrix.config.target == 'traintastic-server'
      uses: actions/upload-artifact@v2
      with:
        name: traintastic-server-deb
        path: ${{runner.workspace}}/server/build/*.deb

    # Code coverage:
    - name: Code coverage
      if: matrix.config.ccov
      working-directory: ${{runner.workspace}}/server/build
      run: make ccov

    - name: "Code coverage: upload artifact"
      if: matrix.config.ccov
      uses: actions/upload-artifact@v2
      with:
        name: traintastic-server-test-code-coverage
        path: ${{runner.workspace}}/server/build/ccov/*

  package-innosetup:
    name: package innosetup
    runs-on: windows-latest
    needs: [build-client, build-server]

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Download artifacts 1/2
      uses: actions/download-artifact@v2
      with:
        name: traintastic-client
        path: ${{github.workspace}}/build-client

    - name: Download artifacts 2/2
      uses: actions/download-artifact@v2
      with:
        name: traintastic-server
        path: ${{github.workspace}}/build-server/Release

    - name: Build installer
      shell: cmd
      run: |
        "C:/Program Files (x86)/Inno Setup 6/ISCC.exe" %GITHUB_WORKSPACE%/package/innosetup/traintastic.iss /Ftraintastic-setup-%CI_REF_NAME_SLUG%-${{github.run_number}}-%CI_SHA_SHORT%

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-innosetup
        path: ${{github.workspace}}/package/innosetup/output

  deploy:
    name: Deploy to website
    runs-on: ubuntu-20.04
    needs: [package-innosetup, build-server, build-client]

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Download artifacts 1/4
      uses: actions/download-artifact@v2
      with:
        name: package-innosetup
        path: dist

    - name: Download artifacts 2/4
      uses: actions/download-artifact@v2
      with:
        name: traintastic-client-deb
        path: dist

    - name: Download artifacts 3/4
      uses: actions/download-artifact@v2
      with:
        name: traintastic-server-deb
        path: dist

    - name: Download artifacts 4/4
      uses: actions/download-artifact@v2
      with:
        name: traintastic-server-test-code-coverage
        path: dist/ccov

    - uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/*"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}/traintastic/${{env.CI_REF_NAME_SLUG}}/${{github.run_number}}/
